import {TwinScene} from './scene.js?v=8';
import {createSimulation} from './simulation.js?v=5';
import {faultLabels,supportedFaults,faultExplanation,createFaultDrafts} from './fault-options.js';
import {mountNavigationHelp} from '../viewer-v2/navigation-ui.js';
import {createFocusHistory,shouldAutoFocus} from './focus-history.js';
import {createManufacturing} from './manufacturing.js?v=6';
import {ManufacturingPanel} from './manufacturing-ui.js?v=8';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={HQ:'行政研发楼',FAB1:'FAB 1 主厂房',FAB2:'FAB 2 扩建预留（示意）',LAB:'LAB 实验楼',MASK:'MASK 厂房',EXHIBITION:'展示中心',DINING_E:'东侧餐厅',DINING_W:'西侧餐厅'};
const kinds={breaker:'配电开关',light:'可调光灯组',ahu:'空调 / 通风机组',pump:'循环泵',valve:'调节阀',sensor:'环境 / 设备传感器',load:'设备负载 · 由配电回路控制'};
const qualities={good:'在线 · 反馈正常',offline:'通信离线 · 数据陈旧',fault:'设备故障',unavailable:'上游不可用 / 断电'};
const statuses={pending:'待执行',applied:'已执行 · 等待反馈',confirmed:'反馈确认',rejected:'执行拒绝',timeout:'反馈超时',failed:'执行失败'};
let layout,sim,assets,building='FAB1',selected,roomId=null,snapshot,scene,lastCommandId,toastTimer,loadingTicket=0,uiTime=0,simTime=0,activePanel='topology';
let selectionComponent=null,manufacturingSpec,manufacturing,manufacturingPanel,manufacturingTime=0;
let selectionModelId=null,autoFocus=false,assetDomain='all';
try{autoFocus=localStorage.getItem('phoenix-twin-auto-focus')==='true';}catch{}
const focusHistory=createFocusHistory(),expandedRooms=new Set();
const faultDrafts=createFaultDrafts();
const number=(n,d=1)=>n!==null&&n!==undefined&&Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
const time=t=>{t=Math.floor(t||0);return `${String(Math.floor(t/3600)).padStart(2,'0')}:${String(Math.floor(t/60)%60).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function listForBuilding(){return [...assets.values()].filter(a=>a.buildingId===building);}
function roomList(){return layout.rooms.filter(r=>r.buildingId===building);}
function stateFor(id){return snapshot?.assets[id]||snapshot?.circuits[id];}
function switchPanel(key){activePanel=key;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===key));for(const name of ['manufacturing','topology','trend','events','alarms'])$('panel-'+name).hidden=name!==key;}
function showManufacturing(){rememberObservation();scene.setView('production');syncViewControls();switchPanel('manufacturing');updateUI();}
function syncFocusControls(){
 $('auto-focus').checked=autoFocus;$('browse-mode-note').textContent=autoFocus?'浏览模式：列表选中后聚焦。点击模型保持视角。':'观察模式：选中只更新控制台，画面保持不变。';
 $('return-observation').disabled=!focusHistory.size;$('focus-device').textContent=scene?.pickedInspection?'⌖ 聚焦点击位置':'⌖ 聚焦选中物件';document.querySelector('.selection-actions span').textContent=scene?.pickedInspection?'查看点击处局部；列表定位可看完整构件':'查看位置，不影响运行设定';
}
function rememberObservation(){focusHistory.remember(scene);syncFocusControls();}
function focusAsset(id=selected){
 const a=assets.get(id),target=id===selected&&selectionModelId?selectionModelId:a?.type==='circuit'?a.upstreamPanelId:id;
 if(!target)return;rememberObservation();const result=scene.focusDevice(target);syncViewControls();syncFocusControls();if(result===false)toast('该节点尚无可定位的三维构件。');
}
function focusSelected(){focusAsset(selected);}
function focusRoom(id,{remember=true}={}){if(remember)rememberObservation();scene.focusRoom(id);syncViewControls();syncFocusControls();}
function renderBrowser(){
 const query=$('search').value.trim().toLowerCase(),all=listForBuilding().filter(a=>assetDomain==='all'||(assetDomain==='manufacturing'?a.manufacturing:!a.manufacturing));$('asset-count').textContent=`${all.length} 个节点`;
 const groups=[{id:null,label:'公共配电与水系统',level:'PLANT'},...roomList()];
 $('room-list').innerHTML=groups.map(r=>{const devices=all.filter(a=>(a.roomId||null)===r.id&&(!query||`${a.label} ${a.id}`.toLowerCase().includes(query)));if(!devices.length)return '';const open=expandedRooms.has(r.id)||Boolean(query);return `<div class="room-item"><div class="room-heading"><button class="room-button ${roomId===r.id?'active':''}" data-room="${r.id||''}" aria-expanded="${open}"><span>${escape(r.label)}</span><small>${escape(r.level)} ${open?'−':'+'}</small></button><button class="room-focus" data-room-focus="${r.id||''}" title="查看${escape(r.label)}" aria-label="查看${escape(r.label)}">查看</button></div><div class="device-list" ${open?'':'hidden'}>${devices.map(a=>`<div class="asset-row"><button class="asset-button ${selected===a.id?'active':''}" data-asset="${a.id}"><i class="lamp"></i><span class="asset-label">${escape(a.label)}</span><span class="mini">${a.manufacturing?'制造':a.type==='circuit'?'分路':a.controlKind?'控制':'监测'}</span></button><button class="asset-focus" data-focus-asset="${a.id}" title="聚焦${escape(a.label)}" aria-label="聚焦${escape(a.label)}">⌖</button></div>`).join('')}</div></div>`;}).join('');
 $('room-list').querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>selectRoom(b.dataset.room||null,{toggle:true}));$('room-list').querySelectorAll('[data-room-focus]').forEach(b=>b.onclick=()=>selectRoom(b.dataset.roomFocus||null,{focus:true}));$('room-list').querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>selectAsset(b.dataset.asset,{source:'list'}));$('room-list').querySelectorAll('[data-focus-asset]').forEach(b=>b.onclick=()=>{selectAsset(b.dataset.focusAsset,{source:'focus'});focusAsset(b.dataset.focusAsset);});
}
function selectRoom(id,{toggle=false,focus=autoFocus,remember=true}={}){roomId=id;const open=!expandedRooms.has(id);if(toggle&&!open)expandedRooms.delete(id);else expandedRooms.add(id);if(focus&&(!toggle||open))focusRoom(id,{remember});renderBrowser();renderRoom();renderTopology();}
function selectAsset(id,detail){
 const a=assets.get(id);if(!a){if(detail?.component)selectComponent(id,detail);return;}selectionComponent=null;document.querySelector('.inspector').scrollTop=0;selected=id;roomId=a.roomId||null;expandedRooms.add(roomId);lastCommandId=stateFor(id)?.lastCommandId;
 selectionModelId=detail?.componentId||(a.type==='circuit'?a.upstreamPanelId:id);scene.select(selectionModelId,detail);syncFocusControls();if(shouldAutoFocus({enabled:autoFocus,source:detail?.source}))focusAsset(id);
 document.querySelector('.feedback-grid').hidden=false;document.querySelector('.fault-lab').hidden=false;
 $('selection-empty').hidden=true;$('selection').hidden=false;$('device-kind').textContent=a.manufacturing?({tool:'代表工艺设备',loadport:'晶圆装载口',carrier:'FOUP 载具',oht:'高架运输车',stocker:'自动仓储',rail:'高架轨道'})[a.kind]:kinds[a.controlKind||a.type]||a.sensorKind||'设备节点';$('device-name').textContent=a.label;$('device-id').textContent=a.id;
 const r=layout.rooms.find(r=>r.id===a.roomId);$('device-meta').textContent=[names[a.buildingId],r?.label||'建筑公共系统',a.circuitId?`回路 ${a.circuitId}`:'',a.waterBranchId?`水路 ${a.waterBranchId}`:''].filter(Boolean).join(' / ');
 $('manufacturing-inspector').hidden=!a.manufacturing;manufacturingPanel.inspected=null;
 if(a.manufacturing){document.querySelector('.feedback-grid').hidden=true;document.querySelector('.fault-lab').hidden=true;$('command-controls').hidden=true;$('observations').replaceChildren();manufacturingPanel.mountInspector(a);switchPanel('manufacturing');renderBrowser();renderRoom();return;}
 const s=stateFor(id);$('command-controls').hidden=!a.controlKind;$('mode').value=s?.desired?.mode||'auto';$('set-value').value=s?.desired?.value??100;$('set-output').textContent=$('set-value').value+'%';$('set-value').step=a.controlKind==='breaker'?'100':'5';$('set-label').textContent=({light:'灯光亮度',valve:'阀门开度',pump:'泵转速',ahu:'风机设定',breaker:'开关状态'})[a.controlKind]||'设定值';$('set-temperature').value=s?.desired?.setpoint??24;$('temperature-control').hidden=a.controlKind!=='ahu';
 const choices=supportedFaults(a);$('fault-type').replaceChildren(...choices.map(kind=>new Option(faultLabels[kind],kind)));$('fault-type').value=faultDrafts.value(a);$('fault-type').hidden=!choices.length;$('fault-explanation').textContent=faultExplanation(a);$('inject-fault').disabled=!choices.length;$('clear-fault').disabled=!choices.length;
 renderBrowser();renderSelected();renderRoom();renderTopology();
}
function selectComponent(id,detail){
 $('manufacturing-inspector').hidden=true;manufacturingPanel.inspected=null;
 const c=detail.component;selectionComponent=detail;selected=id;roomId=c.meta?.roomId||null;expandedRooms.add(roomId);lastCommandId=null;selectionModelId=detail.componentId||id;scene.select(selectionModelId,detail);syncFocusControls();document.querySelector('.inspector').scrollTop=0;
 $('selection-empty').hidden=true;$('selection').hidden=false;$('device-kind').textContent='CAD 构件 · 可检视';$('device-name').textContent=c.label||id;$('device-id').textContent=id;
 $('device-meta').textContent=[names[building],c.level,c.system].filter(Boolean).join(' / ');$('device-status').textContent='静态构件';$('device-status').className='';$('device-mode').textContent='未配置独立运行点位';
 document.querySelector('.feedback-grid').hidden=true;$('command-controls').hidden=true;document.querySelector('.fault-lab').hidden=true;
 $('command-receipt').textContent='已选中三维构件。此物件没有独立模拟控制；可通过下方关联设备查看所属系统。';
 $('observations').innerHTML=`<div class="data-row"><span>构件来源</span><b>${c.id.startsWith('V4_')?'室内 / 机电 CAD':'建筑 CAD'}</b></div><div class="data-row"><span>系统</span><b>${escape(c.system||'—')}</b></div>`;
 renderBrowser();renderRoom();renderTopology();
}
async function loadBuilding(id){
 const ticket=++loadingTicket;$('load-mask').hidden=false;$('load-text').textContent=`装配${names[id]}与机电系统…`;
 try{if(!await scene.load(id,layout)||ticket!==loadingTicket)return;building=id;document.querySelector('.asset-browser').scrollTop=0;selected=null;selectionModelId=null;focusHistory.clear();expandedRooms.clear();roomId=roomList()[0]?.id||null;$('building').value=id;$('view-label').textContent=`${names[id]} · 代表房间与服务区`;$('drawing-link').href=`../output/cad-v4/drawings/${id}_systems.svg`;
  const levels=[...new Set(roomList().map(r=>r.level))];$('floor').innerHTML=levels.map(l=>`<option value="${l}">${l} 代表层</option>`).join('')+'<option value="all">全部机电层</option>';$('floor').value=scene.level;
  const hasManufacturing=manufacturingSpec.buildings.some(b=>b.id===id);document.querySelector('[data-asset-domain=manufacturing]').hidden=!hasManufacturing;if(!hasManufacturing&&assetDomain==='manufacturing')assetDomain='all';document.querySelectorAll('[data-asset-domain]').forEach(b=>b.classList.toggle('active',b.dataset.assetDomain===assetDomain));document.querySelector('[data-view=production]').hidden=!hasManufacturing;document.querySelector('[data-panel=manufacturing]').hidden=!hasManufacturing;if(!hasManufacturing&&activePanel==='manufacturing')switchPanel('topology');
  selectRoom(roomId,{focus:true,remember:false});const first=(hasManufacturing?listForBuilding().find(a=>a.manufacturing&&a.kind==='tool'):null)||listForBuilding().find(a=>a.roomId===roomId&&a.controlKind==='light')||listForBuilding()[0];if(first)selectAsset(first.id);
  if(hasManufacturing){scene.setView('production');syncViewControls();switchPanel('manufacturing');manufacturingPanel.update(id,selected);}
  $('load-mask').hidden=true;$('building-note').hidden=id!=='FAB2';history.replaceState(null,'','#'+building);updateUI();
 }catch(error){console.error(error);$('load-text').textContent=`载入失败：${error.message}。可刷新重试。`;toast(error.message);}
}
function syncViewControls(){$('floor').value=scene.level;$('view-label').textContent=names[building]+(scene.view==='production'?' · 代表制造单元 / 物流模拟':' · 代表房间与服务区');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===scene.view));for(const [id,key] of [['show-electric','electrical'],['show-water','water'],['show-hvac','hvac'],['show-labels','labels']])$(id).checked=scene.layers[key];$('explode').value=scene.explode;}
function send(patch){if(!selected)return;try{lastCommandId=sim.command(selected,patch);if(typeof lastCommandId==='object')lastCommandId=lastCommandId.id||lastCommandId.commandId;snapshot=sim.snapshot();renderSelected();renderEvents();const receipt=snapshot.commands.find(c=>c.id===lastCommandId);toast(receipt?.status==='rejected'?'指令被拒绝：'+receipt.reason:'指令已进入模拟控制器，等待执行反馈。');}catch(error){toast(error.message);}}
function renderSelected(){
 if(!selected)return;const a=assets.get(selected);if(a?.manufacturing){manufacturingPanel.renderInspector(a);return;}const s=stateFor(selected);if(!s)return;
 $('device-status').textContent=qualities[s.quality]||s.quality||'回路状态';$('device-status').className=['fault','offline','unavailable'].includes(s.quality)?'fault':'';$('device-mode').textContent=(s.desired?.mode||s.mode)==='manual'?'手动控制':'自动控制';
 const unit=a.controlKind||a.type==='load'?'%':a.unit||s.observed?.unit||'';$('desired').textContent=a.controlKind?`${number(s.desired?.value,0)}%`:'遥测';$('observed').textContent=number(s.observed?.value??s.value,1)+unit;
 const obs=s.observed||{},rows=[['实际功率',obs.powerKw,'kW',2],['流量',obs.flowLpm,'L/min',1],['压力',obs.pressureKpa,'kPa',1],['风量',obs.airflowM3h,'m³/h',0],['温度',obs.temperature,'°C',1],['采样时刻',time(obs.timestamp),'',null]];
 $('observations').innerHTML=rows.filter(r=>r[1]!==undefined&&(!['流量','压力'].includes(r[0])||['valve','pump'].includes(a.controlKind))&&(r[0]!=='风量'||a.controlKind==='ahu')).map(([label,v,u,d])=>`<div class="data-row"><span>${label}</span><b>${d===null?escape(v):number(v,d)} ${u}</b></div>`).join('');
 const cmd=snapshot.commands.find(c=>c.id===(lastCommandId||s.lastCommandId))||snapshot.commands.find(c=>c.assetId===selected);$('command-receipt').textContent=cmd?`${cmd.id} · ${statuses[cmd.status]||cmd.status}${cmd.reason?' / '+cmd.reason:''}`:'尚未下发操作。当前显示模拟控制器的运行状态。';
}
function renderRoom(){
 const r=layout.rooms.find(r=>r.id===roomId),s=snapshot.rooms[roomId];$('room-title').textContent=r?`${r.label} · 空间环境`:'公共系统 · 建筑环境';const v=s||snapshot.buildingMetrics[building]||{};const values=[['室温',v.temperature,'°C'],['相对湿度',v.humidity,'%'],['CO₂',v.co2,'ppm'],['模拟照度',v.illuminationLux??v.illuminanceLux,'lx'],['用电功率',v.powerKw,'kW'],['供水流量',v.waterFlowLpm,'L/min'],['工艺冷却循环',v.coolingFlowLpm,'L/min'],['送 / 排风量',v.airflowM3h,'m³/h'],['运行条件指数',v.processAvailability!==undefined?v.processAvailability*100:undefined,'%（模拟）']];$('room-data').innerHTML=values.filter(x=>x[1]!==undefined).map(([l,v,u])=>`<div class="data-row"><span>${l}</span><b>${number(v)} ${u}</b></div>`).join('');
}
function topologyIds(a){const ids=[],seen=new Set();function visit(id){if(!id||seen.has(id))return;seen.add(id);const item=assets.get(id);if(!item)return;for(const p of item.upstreamIds||[])visit(p);if(item.circuitId)visit(item.circuitId);if(item.upstreamPanelId)visit(item.upstreamPanelId);ids.push(id);}if(a?.waterBranchId){let b=layout.waterBranches.find(b=>b.id===a.waterBranchId);const chain=[],guard=new Set();while(b&&!guard.has(b.id)){guard.add(b.id);chain.unshift(b);b=layout.waterBranches.find(q=>q.id===b.upstreamBranchId);}for(const b of chain)for(const id of [...b.valveIds,...b.pumpIds])if(id!==a.id)visit(id);}if(a)visit(a.id);return ids;}
function renderTopology(){
 if(selectionComponent){const related=(selectionComponent.relatedAssetIds||[]).filter(id=>assets.has(id));$('topology').innerHTML=related.map(id=>`<button class="topology-node" data-node="${escape(id)}">${escape(assets.get(id).label)}<small>${escape(id)}</small></button>`).join('')+`<div class="topology-note">${related.length?'点击关联设备进入所属电路或水路的控制与反馈。':'此构件只有 CAD 几何，尚无独立设备状态或运输任务。'}</div>`;$('topology').querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>selectAsset(b.dataset.node));return;}
 const a=assets.get(selected),ids=topologyIds(a);const r=layout.rooms.find(r=>r.id===roomId);if(!ids.length&&r)ids.push(r.panelId,...r.circuitIds);const affected=selected?listForBuilding().filter(b=>(b.upstreamIds||[]).includes(selected)||b.circuitId===selected):[];
 const buttons=ids.map((id,i)=>{const q=assets.get(id),s=stateFor(id);return `${i?'<span class="topology-arrow">→</span>':''}<button class="topology-node ${id===selected?'active':''} ${s?.quality==='fault'?'fault':''}" data-node="${id}">${escape(q?.label||id)}<small>${s?.observed?number(s.observed.value,0)+'%':s?.energized?'通电':'状态联动'} · ${escape(q?.controlKind==='breaker'?'配电':q?.waterBranchId?'水路':'设备')}</small></button>`;}).join('');
 $('topology').innerHTML=buttons+`<div class="topology-note">${affected.length?`该节点有 ${affected.length} 个直接下游设备。点击节点可操作；断电与水路关闭会沿关系传播。`:'按资产编号串联的概念拓扑。箭头表示依赖方向；管线几何与设备节点可在三维中检视。'}${a?.waterBranchId?' 供水、热水、排水及 PCW 分开建模。':''}</div>`;$('topology').querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>selectAsset(b.dataset.node));
}
function renderEvents(){const rows=snapshot.events.filter(e=>!e.buildingId||e.buildingId===building||assets.get(e.assetId)?.buildingId===building).slice(0,50);$('events').innerHTML=rows.length?rows.map(e=>`<div class="event-row"><time>${time(e.time??e.timestamp)}</time><span>${escape(e.message||e.type||e.action)}${e.assetId?' · '+escape(e.assetId):''}</span><b class="event-state">${escape(statuses[e.status]||e.status||'')}</b></div>`).join(''):'<p class="empty-message">尚无命令。选择设备后下发设定，可查看执行和反馈记录。</p>';}
function renderAlarms(){const rows=snapshot.alarms.filter(a=>a.buildingId===building||assets.get(a.assetId)?.buildingId===building);$('alarms').innerHTML=rows.length?rows.map(a=>`<div class="alarm-row ${a.active?'active':''}"><span>${escape(a.message)}<br><small>${escape(a.assetId||'')} · ${a.active?'活动':'已恢复'} / ${a.acknowledged?'已确认':'未确认'}</small></span>${!a.acknowledged?`<button data-ack="${a.id}">确认</button>`:''}<button data-locate="${a.assetId}">定位</button></div>`).join(''):'<p class="empty-message">当前没有告警。故障演练后可在这里确认与定位；确认不会清除故障。</p>';$('alarms').querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>{sim.ackAlarm(b.dataset.ack);snapshot=sim.snapshot();renderAlarms();});$('alarms').querySelectorAll('[data-locate]').forEach(b=>b.onclick=()=>{selectAsset(b.dataset.locate,{source:'alarm'});focusAsset(b.dataset.locate);});}
function renderTrends(){const data=snapshot.trends?.buildings?.[building]||[];const defs=[['powerKw','用电功率','kW','#e3b969'],['temperature','室温','°C','#91c8b7'],['waterFlowLpm','供水流量','L/min','#76c5d0']];$('trends').innerHTML=defs.map(([key,label,unit,color])=>{const values=data.slice(-120).map(x=>Number(x[key]||0));const min=Math.min(...values,0),max=Math.max(...values,1),span=max-min||1;const points=values.map((v,i)=>`${(i/Math.max(values.length-1,1)*290+4).toFixed(1)},${(83-(v-min)/span*65).toFixed(1)}`).join(' ');return `<div class="chart"><div><span>${label}</span><b>${number(values.at(-1))} ${unit}</b></div><svg viewBox="0 0 300 100" role="img" aria-label="${label}运行趋势"><path d="M4 18H294 M4 51H294 M4 83H294" stroke="#2e4851" fill="none"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="2"/><text x="5" y="12">${number(max)}</text><text x="5" y="98">${number(min)}</text></svg></div>`;}).join('');}
function updateUI(){snapshot=sim.snapshot();const elapsed=Math.max(0,snapshot.time-manufacturingTime);if(elapsed>0)manufacturing.tick(elapsed,snapshot);manufacturingTime=snapshot.time;const production=manufacturing.snapshot();manufacturingPanel.update(building,selected,production);scene.updateManufacturing(production);$('clock').textContent=time(snapshot.time);const b=snapshot.buildingMetrics[building]||{};$('k-power').textContent=number(b.powerKw);$('k-temp').textContent=number(b.temperature);$('k-water').textContent=number(b.waterFlowLpm);const alarms=snapshot.alarms.filter(a=>a.active&&(a.buildingId===building||assets.get(a.assetId)?.buildingId===building));$('k-alarm').textContent=alarms.length;$('k-alarm').classList.toggle('alarm',alarms.length>0);$('alarm-badge').textContent=alarms.length;$('k-feedback').textContent=`模拟遥测 · ${time(snapshot.time)}`;renderSelected();renderRoom();if(activePanel==='trend')renderTrends();if(activePanel==='events')renderEvents();if(activePanel==='alarms')renderAlarms();if(activePanel==='topology')renderTopology();$('room-list').querySelectorAll('[data-asset]').forEach(b=>{const s=stateFor(b.dataset.asset)||production.assetStates[b.dataset.asset];b.classList.toggle('fault',s?.quality==='fault'||Boolean(s?.fault||s?.blocked));b.classList.toggle('offline',s?.quality==='offline'||s?.quality==='unavailable');});scene.updateTelemetry(snapshot);$('render-info').textContent=`${Math.round(scene.stats.triangles/1000)}k 三角面 · ${scene.stats.calls} 次绘制`;}
function wire(){
 document.querySelectorAll('[data-asset-domain]').forEach(b=>b.onclick=()=>{assetDomain=b.dataset.assetDomain;document.querySelectorAll('[data-asset-domain]').forEach(q=>q.classList.toggle('active',q===b));renderBrowser();});
 $('auto-focus').onchange=e=>{autoFocus=e.target.checked;try{localStorage.setItem('phoenix-twin-auto-focus',String(autoFocus));}catch{}syncFocusControls();};$('return-observation').onclick=()=>{if(focusHistory.back(scene)){syncViewControls();syncFocusControls();toast('已返回先前观察视角，当前设备选择与运行状态保持不变。');}};syncFocusControls();
 $('building').onchange=e=>loadBuilding(e.target.value);$('search').oninput=renderBrowser;$('floor').onchange=e=>{roomId=null;scene.setFloor(e.target.value);syncViewControls();renderBrowser();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='production'){showManufacturing();return;}scene.setView(b.dataset.view);syncViewControls();});$('fit').onclick=()=>{roomId=null;scene.focusRoom(null);syncViewControls();renderBrowser();};
 for(const id of ['show-electric','show-water','show-hvac','show-labels','explode'])$(id).oninput=()=>scene.setLayers({electrical:$('show-electric').checked,water:$('show-water').checked,hvac:$('show-hvac').checked,labels:$('show-labels').checked},Number($('explode').value));
 $('set-value').oninput=e=>{$('set-output').textContent=e.target.value+'%';$('mode').value='manual';};$('send').onclick=()=>send({mode:$('mode').value,value:Number($('set-value').value),...(assets.get(selected)?.controlKind==='ahu'?{setpoint:Number($('set-temperature').value)}:{})});$('on').onclick=()=>{$('mode').value='manual';$('set-value').value=100;$('set-output').textContent='100%';send({mode:'manual',value:100});};$('off').onclick=()=>{$('mode').value='manual';$('set-value').value=0;$('set-output').textContent='0%';send({mode:'manual',value:0});};$('mode').onchange=e=>{if(e.target.value==='auto')send({mode:'auto'});};$('focus-device').onclick=focusSelected;
 $('fault-type').onchange=e=>faultDrafts.set(assets.get(selected),e.target.value);
 $('inject-fault').onclick=()=>{try{const kind=$('fault-type').value;if(!supportedFaults(assets.get(selected)).includes(kind))return;faultDrafts.set(assets.get(selected),kind);sim.injectFault(selected,kind);updateUI();toast(`已注入模拟故障：${faultLabels[kind]}。`);}catch(e){toast(e.message);}};$('clear-fault').onclick=()=>{sim.clearFault(selected);updateUI();toast('故障原因已排除；设备按当前设定逐步恢复。');};
 $('pause').onclick=()=>{sim.setPaused(!sim.snapshot().paused);$('pause').textContent=sim.snapshot().paused?'继续':'暂停';updateUI();};$('speed').onchange=e=>sim.setSpeed(Number(e.target.value));$('reset').onclick=()=>{sim.reset();manufacturing.reset();manufacturingTime=0;sim.setSpeed(Number($('speed').value));$('pause').textContent='暂停';lastCommandId=null;updateUI();if(selected)selectAsset(selected);toast('全部模拟状态已重置。');};
 document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{switchPanel(b.dataset.panel);updateUI();});
 $('export').onclick=()=>{const data={schema:'campus-twin-snapshot/6',source:'local-simulation-only',coverage:layout.coverage,building,selected,simulation:sim.snapshot(),manufacturing:manufacturing.snapshot(),manufacturingScope:manufacturingSpec.scope};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='phoenix-twin-'+building+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('模拟快照已导出，包含设定、反馈、告警、拓扑状态与趋势。');};
}
async function init(){
 const [response,manufacturingResponse]=await Promise.all([fetch('../analysis/v4/mep-layout.json'),fetch('../analysis/v6/manufacturing-layout.json')]);if(!response.ok)throw Error('无法读取机电设计清单');layout=await response.json();assets=new Map([...layout.controlAssets,...layout.sensors,...(layout.electricalLoads||[]),...layout.circuits.map(c=>({...c,type:'circuit',controlKind:'breaker',upstreamIds:[c.upstreamPanelId]}))].map(a=>[a.id,a]));
 if(!manufacturingResponse.ok)throw Error('无法读取制造设计清单');manufacturingSpec=await manufacturingResponse.json();for(const a of manufacturingSpec.assets)assets.set(a.id,{...a,manufacturing:true});manufacturing=createManufacturing(manufacturingSpec);manufacturingPanel=new ManufacturingPanel(manufacturing,manufacturingSpec,{select:id=>selectAsset(id,{source:'list'}),show:showManufacturing,toast,onChange:updateUI});
 sim=createSimulation(layout,{historyLimit:120});sim.setSpeed(5);snapshot=sim.snapshot();scene=new TwinScene($('stage'),$('room-labels'),selectAsset);scene.manufacturingSpec=manufacturingSpec;mountNavigationHelp($('stage'),scene.keyboard);$('building').innerHTML=Object.entries(names).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');wire();const requested=location.hash.slice(1);if(names[requested])building=requested;$('building').value=building;await loadBuilding(building);
 window.twinV4={sim,scene,layout,manufacturing,manufacturingSpec,get snapshot(){return sim.snapshot();},get selected(){return selected;},get building(){return building;},focusSelected,get autoFocus(){return autoFocus;},get focusHistorySize(){return focusHistory.size;}};
 let last=performance.now();setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,1);last=now;if(document.hidden||snapshot.paused)return;sim.tick(dt);updateUI();},250);
}
init().catch(e=>{console.error(e);$('load-text').textContent='启动失败：'+e.message;});
